title: Art Information Commons
description: A Philadelphia Museum of Art intitiative that aims to transform the way we holistically manage our collections-related data and support a sustainable information culture.

url: https://artinformationcommons.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

theme: brianmaierjr/long-haul

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: About
    url: /index
  - title: Who We Are
    url: /who-we-are
  - title: Updates & Activities
    url: /updates-activities
  - title: Events & Conferences
    url: /events-conferences/
  - title: Resources
    url: /resources
  - title: Toolkit
    url: /toolkit

social:
  github: --
  twitter: --
  facebook: --
  email: Juliet.Vinegra@philamuseum.org

google_analytics: "UA-58263416-1"
